@ECHO OFF
IF %1. == . GOTO BuildDebug
IF %1. == debug. GOTO BuildDebug
IF %1. == DEBUG. GOTO BuildDebug
IF %1. == release. GOTO BuildRelease
IF %1. == RELEASE. GOTO BuildRelease
IF %1. == clean. GOTO Clean
IF %1. == CLEAN. GOTO Clean
IF %1. == spotless. GOTO Spotless
IF %1. == SPOTLESS. GOTO Spotless

ECHO Target Unknown
GOTO Done

:BuildRelease
CD SRC
NMAKE /F WIN32CI.MAK CFG="Win32 Release"
CD ..
GOTO DoneBuilding

:BuildDebug
CD SRC
NMAKE /F WIN32CI.MAK CFG="Win32 Debug"
CD ..
GOTO DoneBuilding

:DoneBuilding
COPY SRC\NETCI.EXE .\NETCI.EXE
IF NOT EXIST NETCI.INI COPY SRC\NETCI.INI .\NETCI.INI
GOTO Done

:Clean
ECHO Y|DEL SRC\WINREL\*.*
RMDIR SRC\WINREL
ECHO Y|DEL SRC\WINDEBUG\*.*
RMDIR SRC\WINDEBUG
DEL SRC\NETCI.EXE
DEL NETCI.EXE
GOTO Done

:Spotless
ECHO Y|DEL SRC\WINREL\*.*
RMDIR SRC\WINREL
ECHO Y|DEL SRC\WINDEBUG\*.*
RMDIR SRC\WINDEBUG
DEL SRC\NETCI.EXE
DEL NETCI.EXE
DEL STD.DB
DEL SYSLOG.TXT
DEL NETCI.INI
DEL CI200FS\ETC\PKG\PACKAGES.LST

:Done

