//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NETCI.RC
//
#define IDE_BROADCAST                   1000
#define IDT_BCMSG                       1001
#define IDB_DONE                        1002
#define IDE_SPROT                       1004
#define IDE_SLOAD                       1005
#define IDE_SSAVE                       1006
#define IDE_SSYSLOG                     1007
#define IDE_SCACHE                      1008
#define IDE_STEMP                       1009
#define IDE_SPANIC                      1010
#define IDE_SSCM                        1012
#define IDE_SHCM                        1013
#define IDE_SMFF                        1014
#define IDE_SMC                         1015
#define IDE_SWB                         1016
#define IDE_SMOL                        1017
#define IDE_SCS                         1019
#define IDE_SCH                         1020
#define IDE_SOAB                        1021
#define IDE_SNE                         1022
#define IDE_SMSL                        1023
#define IDE_SE                          1024
#define IDE_SMD                         1025
#define IDE_SDI                         1026
#define IDE_SMUDLIB                     1027
#define IDT_ABOUT_VERSION               1028
#define IDLB_SWA                        1030
#define IDLB_SFDL                       1031
#define IDLB_SEL                        1032
#define IDT_SELECTMSG1                  1033
#define IDT_SELECTMSG2                  1034
#define IDT_SELECTMSG3                  1035
#define IDLB_CONLIST                    1038
#define IDB_BOOT                        1040
#define IDT_CONMSG1                     1042
#define IDB_VIEW                        1043
#define IDLB_VARS                       1050
#define IDE_DEVNUM                      1052
#define IDE_IPADDR                      1053
#define IDE_FLAGS                       1054
#define IDLB_REFS                       1061
#define IDLB_VERBS                      1062
#define IDB_LOAD                        1063
#define IDB_DESTROY                     1064
#define IDE_CACHESTATUS                 1065
#define IDB_MOVE                        1066
#define IDE_OBJECTSELECTION             1067
#define IDB_REFNO                       1068
#define IDB_PATH                        1069
#define IDB_PARENT                      1071
#define IDB_NEXTCHILD                   1072
#define IDB_LOCATION                    1073
#define IDB_CONTENTS                    1074
#define IDB_NEXTOBJECT                  1075
#define IDB_FLAGS                       1076
#define IDE_PATH                        1078
#define IDLB_FUNCS                      1079
#define IDLB_GLOBALS                    1081
#define IDE_FUNCTION                    1082
#define IDT_STATICMSG                   1085
#define IDE_NUMARGS                     1086
#define IDE_NUMLOCALS                   1087
#define IDLB_CODE                       1088
#define IDB_NEXTPROTO                   1090
#define IDLB_PROTOSELECTION             1091
#define IDB_OBJECT                      1092
#define IDCB_CONNECTED                  1094
#define IDCB_GARBAGE                    1095
#define IDCB_INEDITOR                   1096
#define IDCB_INTERACTIVE                1097
#define IDCB_PRIV                       1098
#define IDCB_PROTOTYPE                  1099
#define IDCB_RESIDENT                   1100
#define IDRB_INTEGER                    1101
#define IDRB_STRING                     1102
#define IDRB_OBJECT                     1103
#define IDE_VARIABLE                    1104
#define IDLB_LIST                       1106
#define IDT_TEXT                        1107
#define IDB_NEW                         1110
#define IDB_DELETE                      1111
#define IDE_DELAY                       1116
#define IDE_OBJECT                      1117
#define IDE_COMMAND                     1119
#define IDB_HIDE                        1120
#define IDB_UNHIDE                      1121
#define IDB_BACK                        1123
#define IDE_FILE                        1124
#define IDB_OWNER                       1126
#define IDLB_CONTENTS                   1127
#define IDCB_DIRECTORY                  1129
#define IDCB_READ                       1130
#define IDCB_WRITE                      1131
#define IDE_OWNER                       1136
#define IDB_MODIFY                      1137
#define IDT_ABOUT_INFO                  1139
#define IDE_SPORT                       1141
#define IDE_SLOGSIZE                    1142
#define IDM_SAVE                        40001
#define IDM_SHUTDOWN                    40002
#define IDM_PANIC                       40003
#define IDM_RTSET                       40004
#define IDM_CONNECTIONS                 40005
#define ID_OUTPUTWIN                    40006
#define IDM_DMON                        40007
#define IDM_MEMUSAGE                    40008
#define IDM_DMOFF                       40009
#define IDM_CTSET                       40010
#define IDM_BROADCAST                   40011
#define IDM_PAUSE                       40012
#define IDM_ABOUT                       40013
#define IDM_UNPAUSE                     40014
#define IDM_SELECT                      40015
#define IDM_OBJECT                      40016
#define IDM_PROTO                       40017
#define IDM_ALARM                       40018
#define IDM_COMMAND                     40019
#define IDM_DESTRUCT                    40020
#define IDM_FILESYSTEM                  40021
#define IDM_AUTOLOAD                    40022

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40023
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
